### ISSUE TITLE
Add Jacobian field to StochSystem

### ISSUE THREAD

**Issue by oameye** [JuliaDynamics/CriticalTransitions.jl#28]
In many algorithms one needs the jacobian of the drift field. These are now computed using ForwardDiff. Adding the the field `jacobian` to `StochSystem`, makes it possible for the user to hardcode it or compute it symbolically using, e.g.,  ModeligToolkit.

**Comment by reykboerner** [comment]
Agreed, integration of ModelingToolkit and the possibility to hardcode the Jacobian of the drift should be included.

**Comment by oameye** [comment]
A jacobian can be stored in `sde.integ.f.jac`

**Comment by oameye** [comment]
Als see https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/issues/228

**Comment by Datseris** [comment]
probably worth coordinating creating the jacobian of a dynamic rule. I do it on my own in `TangentDynamicalSystem` via ForwardDiff. How does `integ.f.jac` do it?

**Comment by Datseris** [comment]
> Would be nice that `jacobian(sde::CoupledSDEs)` works, just as `jacobian(sde::CoupledODEs)`. We just need to make `CoupledSDEs <: CoreDynamicalSystem`. For some reason `CoupledODEs <: CoreDynamicalSystem`, but I don't see where that's defined.

You can define `jacobian(sde::CoupledSDEs) = jacobian(CoupledODEs(sde))` which to me sounds more correct. Because you refer to the jacobian of the drift, while of course one could ask for the jacobian of the noise term just as well.



> `integ.f.jac` stores the jacobian if you define the system with ModelingToolkit and use `jac=true` in the ODESystem. In the background it just uses `Symbolics.build_function` to compile the Symbolics.

Oh, I didn't know that. THat is very useful. DynamicalSystems.jl already supports MTK-made models throughout. So we can add one more option so that if there is a symbolic Jacobian, it uses this one instead of making a forward-diff one. Easy to do via a PR if you are interested!

**Comment by oameye** [comment]
@Datseris made a [PR](https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/pull/229)

**Comment by oameye** [comment]
This should be resolved by https://github.com/JuliaDynamics/DynamicalSystemsBase.jl/pull/229
